### ISSUE TITLE
Create a new route

### ISSUE THREAD

**Issue by sriram2k4** [sriram2k4/todoListAPI#1]
Create a route to delete all the todos in the server.js file

**Comment by Sky-De** [comment]
Hi @sriram2k4 
Simply just add this to server.js file

`// Deleting all todos using delete
app.delete('/todos/delete', (req, res) => {
        todoList = [ ];
        res.status(200).send(todoList);
    }
});`


And send delete request to this endpoint from client
Also it is good practice if you implement middleware for checking user auth before delete all
